# Server Configuration
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://TP_Grupo15:5Cd1S1JjAEcYj4s1@tpgrupo15.g7bd9qy.mongodb.net/forum_bd
spring.data.mongodb.database=forum_bd

# Application Name
spring.application.name=forum_db

# Logging
logging.level.org.springframework.data.mongodb=INFO

# JWT Configuration
jwt.secret=your-256-bit-secret-key-here-must-be-at-least-32-characters-long
jwt.expiration=86400000